/**
 * \file
 *
 * \brief User board configuration template
 *
 */

#ifndef CONF_BOARD_H
#define CONF_BOARD_H

#define DIRA IOPORT_CREATE_PIN(PORTB,0)
#define DIRB IOPORT_CREATE_PIN(PORTB,1)
#define DIRC IOPORT_CREATE_PIN(PORTB,2)
#define DIRD IOPORT_CREATE_PIN(PORTB,3)
#define DIRE IOPORT_CREATE_PIN(PORTB,4)
#define DIRF IOPORT_CREATE_PIN(PORTB,5)

#define LED1 IOPORT_CREATE_PIN(PORTF,4)


#define LED2 IOPORT_CREATE_PIN(PORTD,7)
#define UARTD_TX IOPORT_CREATE_PIN(PORTD,3)
#define UARTD_RX IOPORT_CREATE_PIN(PORTD,2)
#define TXEN IOPORT_CREATE_PIN(PORTD,6)




#define BOARD_XOSC_HZ	16000000
#define BOARD_XOSC_STARTUP_US 100
#define BOARD_XOSC_TYPE XOSC_TYPE_XTAL
#endif // CONF_BOARD_H
